name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Running unit tests
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: rc
          arguments: test

      - name: Test coverage verification
        uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: rc
          arguments: jacocoTestCoverageVerification

      - name: Releasing
        uses: eskatos/gradle-command-action@v1
        env:
          nexusUsername: ${{ secrets.nexusUsername }}
          nexusPassword: ${{ secrets.nexusPassword }}
          signing:
            keyId: ${{ secrets.signingKeyId }}
            password: ${{ secrets.signingPassword }}
            secretKeyRingFile: ${{ secrets.secretKeyRingFile }}
        with:
          gradle-version: rc
          arguments:
            allure-junit5-extensions:uploadArchives allure-junit5-extensions:closeAndReleaseRepository
            allure-rest-assured:uploadArchives allure-rest-assured:closeAndReleaseRepository
            allure-webdriver:uploadArchives allure-webdriver:closeAndReleaseRepository
            allure-steps:uploadArchives allure-steps:closeAndReleaseRepository
            junit5-extensions:uploadArchives junit5-extensions:closeAndReleaseRepository